spring.application.name=Skill12
spring.datasource.url=jdbc:mysql://localhost:3306/skill12db
spring.datasource.username=root
spring.datasource.password=Vaishu@0209

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect